### ISSUE TITLE
Unintuitive error description

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#120]
```
class StringMaxCharTest {
    @Test
    fun `SOme test`() {
        maxChar("a") shouldEqual 'a'
    }
}

fun maxChar(str: String): Char? {
    val map = mutableMapOf<Char, Int>()

    str.forEach {
        map[it] = (map[it] ?: 0)  + 1
    }

    return map.maxBy { it.value }?.key
}
```

Above tests works fine, however when we change our assertion to compare with `String`, not `Char`:
`maxChar("a") shouldEqual "a"`

...we will have a very unintuitive error description
`java.lang.AssertionError: Expected <a>, actual <a>.`

BTW keep in mind that it's quite easy to make such mistake by programmer

**Comment by MarkusAmshove** [comment]
This should be a problem within `kotlin.test`, as we're using their implementation of `assertEquals` in this case.

We could either raise an issue/pr on their side or write our own implementation and formatting as for #121

**Comment by igorwojda** [comment]
I think aising a `kotlin.test`  the issue would be a preferable thing to do. I am not that familiar with `kotlin.test` itself, so I will leave it up to you.

**Comment by danielgomezrico** [comment]
Another issue with this is that when you run the tests from the terminal it just prints AssertionError withouth the description... 

```
DateTests > test date parse fromString changingTimeZones FAILED
    java.lang.AssertionError at DateTests.kt:20
```

**Comment by javatarz** [comment]
@igorwojda: Can you check again? I think `kotlin`'s `assertEquals` has been fixed.

## Test code
```
@Test
fun beReadableWhenFailing() {
    val exception = assertFailsWith<AssertionError> { maxChar("a") shouldEqual "a" }
    val message = exception.message!!

    message shouldNotStartWith "expected: <a> but was: <a>"
    message shouldStartWith "expected: java.lang.String<a> but was: java.lang.Character<a>"
}

private fun maxChar(str: String): Char = str.map { it }.toSet().last()
```

### Response
```
java.lang.AssertionError: expected: java.lang.String<a> but was: java.lang.Character<a>
Expected :java.lang.String<a> 
Actual   :java.lang.Character<a>
```

Seems pretty clear

**Comment by igorwojda** [comment]
@javatarz test still fails for me with the wrong exception. Here is my dependency:

```
testImplementation ("org.amshove.kluent:kluent-android:1.56") {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-reflect'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
```

**Comment by javatarz** [comment]
@igorwojda I didn't try this on an independent project. I must admit, I added this test inside the Kluent repo (specifically, this was under the JVM module, not the android one).

Needs further investigation.

**Comment by igorwojda** [comment]
You can easily reproduce this with my project.
1. Checkout this https://github.com/igorwojda/kotlin-coding-puzzle
2. Open in Android Studio
3. Open [MaxOccurrentChar.kt](https://github.com/igorwojda/kotlin-coding-puzzle/blob/master/app/src/test/java/com/igorwojda/string/maxchar/MaxOccurrentChar.kt)
4. Replace file content with this
```
package com.igorwojda.string.maxchar

import org.junit.Test
import org.amshove.kluent.shouldEqual

class StringMaxCharTest {
    @Test
    fun `SOme test`() {
        maxChar("a") shouldEqual "a"
    }
}

fun maxChar(str: String): Char? {
    val map = mutableMapOf<Char, Int>()

    str.forEach {
        map[it] = (map[it] ?: 0)  + 1
    }

    return map.maxBy { it.value }?.key
}

```

5. Run tests is `StringMaxCharTest`

**Comment by MarkusAmshove** [comment]
I'll have time to look at it at the weekend. @igorwojda you could try this on a new Android project and/or new JVM project and compare the outputs of `gradle dependencies`, there could be a discrepancy between Android and jvm kotlin versions

**Comment by drcolombo** [comment]
If executing
`"a" shouldBeEqualTo 'a'`
and then getting

Unexpected type
Expected: <kotlin.Char> but was: <kotlin.String>
Expected :kotlin.Char
Actual   :kotlin.String

is ok, then I will make a PR.
Basically, before comparing 'actual' and 'expected' we can check if types are the same. If not, then we will throw `ComparisonFailedException` with 'Unexpected type' message.

**Comment by MarkusAmshove** [comment]
I like that approach, a PR would be welcome :)
